### ISSUE TITLE
March 20 _ FUNWAVE TVD _ Update file issue

### ISSUE THREAD

**Issue by rezasalatin** [ysboss/agave-model#11]
AttributeError                            Traceback (most recent call last)
~/agave-model/input_box.py in __call__(self, button)
    138         self.obj = obj
    139     def __call__(self,button):
--> 140         updatePara(self.obj.inputTmp,self.obj.outFile,self.obj.form)
    141 
    142 class observe_title:

AttributeError: 'observe_template' object has no attribute 'inputTmp'

**Comment by stevenrbrandt** [comment]
Please issue the following commands:
```
docker-compose down
docker-compose pull
docker-compose up
```
and try again. Let me know if the error persists.

**Comment by rezasalatin** [comment]
yeah it is still there

**Comment by stevenrbrandt** [comment]
Inside model.ipynb, you should see
```
import newmodel
```
Is that what you see? Or are you still importing model? If the latter, please change it to newmodel, try again, and let me know.

**Comment by rezasalatin** [comment]
This page appears is my browser.

![image](https://user-images.githubusercontent.com/43686051/77229313-92f9cc00-6b63-11ea-93c8-81ef276ebfce.png)

**Comment by rezasalatin** [comment]
One more question. Do I even need to press update input file button? Or does uploading suffice?

**Comment by stevenrbrandt** [comment]
The "update input" processes the template files. If you are not using templates, you don't need to press it.

**Comment by stevenrbrandt** [comment]
I pushed a change which I hope will fix the issue for you. Please do a "docker-compose down" and a "docker-compose up" and try again.

**Comment by rezasalatin** [comment]
Yes, it is working. I ran a model and got the results and plotted.

But one more question. if you go to the following link:
https://fengyanshi.github.io/build/html/setup.html
in section compile, you will see that based on our needs we may recompile the program for different purposes and use that specific compiled file. How are we going to do that here?

**Comment by rezasalatin** [comment]
additionally, I think we'd better delete the update file button once the user wants to upload his own files. When uploading files, the template files and the new files are in one folder. Is there a way to add new folders and upload specific models to those folders and download the results to those folders as well?

**Comment by stevenrbrandt** [comment]
Maybe we can rename the button to say "Run templates" or something? The file you are uploading could be a template.

There is not, currently, a way to add new folders with specific models in them. Can you elaborate on how you'd like that to work?

**Comment by rezasalatin** [comment]
I mean there are a couple of files in the template input folder and as default, the new files are uploaded to that folder. Is there any way to upload new files to a new folder?

**Comment by stevenrbrandt** [comment]
@rezasalatin I believe the original issue that started this ticket is resolved. Is that correct?

**Comment by rezasalatin** [comment]
Yes

**Comment by rezasalatin** [comment]
But I do not see the visualization tap. I believe that I had seen it before. I was wondering if I was missing something.

**Comment by stevenrbrandt** [comment]
Visualization is a separate notebook, not a tab.
