### ISSUE TITLE
The input directory should not be part of the repo

### ISSUE THREAD

**Issue by stevenrbrandt** [ysboss/agave-model#4]
The input directory should not be part of the repo. Instead, there should be an input_funwave.tgz and an input_swan.tgz which can be used to create directories input_funwave/ and input_swan/. However, these directories should only be created if they don't exist.

When a job is submitted, input/ can be created from the appropriate directory (input_funwave/ or input_swan/) and then it can be zipped, tarred, and sent for processing.

This change will keep edited files out of the repo, so that "git pull" will not interfere with what users are doing. The system will, however, be able to provide defaults if needed.

**Comment by ysboss** [comment]
Finished it.
